"""create all tables

Revision ID: 15f3fadfea82
Revises: 
Create Date: 2025-11-14 14:51:39.163534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15f3fadfea82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carrito', 'registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_carrito_id'), 'carrito', ['id'], unique=False)
    op.alter_column('compraAbono', 'valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32, asdecimal=2),
               existing_nullable=False)
    op.drop_index('nit_UNIQUE', table_name='entidad')
    op.create_index(op.f('ix_entidad_id'), 'entidad', ['id'], unique=False)
    op.drop_column('entidad', 'correo')
    op.drop_column('entidad', 'direccion')
    op.drop_column('entidad', 'nit')
    op.drop_column('entidad', 'dv')
    op.drop_column('entidad', 'estado')
    op.drop_column('entidad', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entidad', sa.Column('telefono', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('entidad', sa.Column('estado', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True))
    op.add_column('entidad', sa.Column('dv', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True))
    op.add_column('entidad', sa.Column('nit', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('entidad', sa.Column('direccion', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('entidad', sa.Column('correo', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_entidad_id'), table_name='entidad')
    op.create_index('nit_UNIQUE', 'entidad', ['nit'], unique=True)
    op.alter_column('compraAbono', 'valor',
               existing_type=sa.Float(precision=32, asdecimal=2),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_carrito_id'), table_name='carrito')
    op.alter_column('carrito', 'registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###
