"""fix Entidad-Compra relationship

Revision ID: 42af2496d57b
Revises: 15f3fadfea82
Create Date: 2025-11-14 15:09:04.065918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '42af2496d57b'
down_revision: Union[str, None] = '15f3fadfea82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compraAbono', 'valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32, asdecimal=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compraAbono', 'valor',
               existing_type=sa.Float(precision=32, asdecimal=2),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    # ### end Alembic commands ###
