"""Fix model inconsistencies and add missing fields

Revision ID: 6719cf079aa2
Revises: 
Create Date: 2025-11-27 18:38:36.180826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6719cf079aa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('dv', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_index(op.f('ix_entidad_id'), 'entidad', ['id'], unique=False)
    op.create_table('pedidoCupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipoDescuento', sa.Enum('PORCENTAJE', 'MONTO_FIJO', name='tipodescuentoenum'), nullable=False),
    sa.Column('valorDescuento', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('validoDesde', sa.DateTime(), nullable=True),
    sa.Column('validoHasta', sa.DateTime(), nullable=True),
    sa.Column('limiteUso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_pedidoCupon_id'), 'pedidoCupon', ['id'], unique=False)
    op.create_table('pedidoEnvio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('costo', sa.Float(precision=10, asdecimal=2), server_default='0.0', nullable=True),
    sa.Column('tiempoEstimadoEntrega', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidoEnvio_id'), 'pedidoEnvio', ['id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('precioVenta', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=45), server_default='SIMPLE', nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('codbarra', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagenUrl', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEntidad', sa.Integer(), nullable=True),
    sa.Column('sessionToken', sa.String(length=100), nullable=False),
    sa.Column('registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idEntidad'], ['entidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrito_id'), 'carrito', ['id'], unique=False)
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEntidad', sa.Integer(), nullable=False),
    sa.Column('factura', sa.String(length=50), nullable=True),
    sa.Column('subTotal', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('descuento', sa.Float(precision=15, asdecimal=2), server_default='0.0', nullable=True),
    sa.Column('total', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('saldo', sa.Float(precision=15, asdecimal=2), server_default='0.0', nullable=True),
    sa.Column('metodoPago', sa.String(length=15), server_default='DE CONTADO', nullable=True),
    sa.Column('fechaLimite', sa.Date(), nullable=True),
    sa.Column('efectivo', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('transferencia', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('observacion', sa.String(length=100), nullable=True),
    sa.Column('usuario', sa.String(length=10), nullable=True),
    sa.Column('registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idEntidad'], ['entidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_id'), 'compra', ['id'], unique=False)
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Float(precision=12, asdecimal=2), server_default='0.0', nullable=True),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numeroFactura', sa.Integer(), nullable=True),
    sa.Column('idEntidad', sa.Integer(), nullable=False),
    sa.Column('subTotal', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('descuento', sa.Float(precision=15, asdecimal=2), nullable=True),
    sa.Column('montoTotal', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('saldo', sa.Float(precision=15, asdecimal=2), nullable=True),
    sa.Column('estadoPedido', sa.Enum('pendiente', 'procesando', 'enviado', 'entregado', 'cancelado', name='estadopedidoenum'), server_default='pendiente', nullable=True),
    sa.Column('estadoPago', sa.Enum('pendiente', 'pagado', 'fallido', 'reembolsado', name='estadopagoenum'), server_default='pendiente', nullable=True),
    sa.Column('metodoPago', sa.String(length=15), server_default='DE CONTADO', nullable=True),
    sa.Column('direccionEnvio', sa.Text(), nullable=True),
    sa.Column('fechaEntrega', sa.DateTime(), nullable=False),
    sa.Column('idCupon', sa.Integer(), nullable=True),
    sa.Column('idEnvio', sa.Integer(), nullable=True),
    sa.Column('efectivo', sa.Integer(), nullable=True),
    sa.Column('transferencia', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.String(length=10), nullable=True),
    sa.Column('registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEntidad'], ['entidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    op.create_table('productoEnsamble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProductoPadre', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('idProductoHijo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProductoHijo'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['idProductoPadre'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productoEnsamble_id'), 'productoEnsamble', ['id'], unique=False)
    op.create_table('carritoDetalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCarrito', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precioUnitario', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.ForeignKeyConstraint(['idCarrito'], ['carrito.id'], ),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carritoDetalle_id'), 'carritoDetalle', ['id'], unique=False)
    op.create_table('compraAbono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCompra', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(precision=32, asdecimal=2), nullable=False),
    sa.Column('opcionPago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='opcionpagoenum'), server_default='efectivo', nullable=True),
    sa.Column('registro', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['idCompra'], ['compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compraAbono_id'), 'compraAbono', ['id'], unique=False)
    op.create_table('compraDetalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCompra', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('iva', sa.Integer(), server_default='0', nullable=True),
    sa.Column('costoIva', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('totalUnitario', sa.Float(precision=15, asdecimal=2), nullable=True),
    sa.Column('precioVenta', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.ForeignKeyConstraint(['idCompra'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compraDetalle_id'), 'compraDetalle', ['id'], unique=False)
    op.create_table('pedidoDetalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPedido', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precioUnitario', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('resigstro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idPedido'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidoDetalle_id'), 'pedidoDetalle', ['id'], unique=False)
    op.create_table('pedidoPago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPedido', sa.Integer(), nullable=False),
    sa.Column('pasarelaPagoId', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('estadoPago', sa.Enum('PENDIENTE', 'COMPLETADO', 'FALLIDO', name='estadopagoenum'), server_default='pendiente', nullable=True),
    sa.Column('opcionPago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='opcionpagoenum'), server_default='efectivo', nullable=True),
    sa.Column('idTransaccion', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=15), nullable=True),
    sa.Column('registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idPedido'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidoPago_id'), 'pedidoPago', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidoPago_id'), table_name='pedidoPago')
    op.drop_table('pedidoPago')
    op.drop_index(op.f('ix_pedidoDetalle_id'), table_name='pedidoDetalle')
    op.drop_table('pedidoDetalle')
    op.drop_index(op.f('ix_compraDetalle_id'), table_name='compraDetalle')
    op.drop_table('compraDetalle')
    op.drop_index(op.f('ix_compraAbono_id'), table_name='compraAbono')
    op.drop_table('compraAbono')
    op.drop_index(op.f('ix_carritoDetalle_id'), table_name='carritoDetalle')
    op.drop_table('carritoDetalle')
    op.drop_index(op.f('ix_productoEnsamble_id'), table_name='productoEnsamble')
    op.drop_table('productoEnsamble')
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_index(op.f('ix_compra_id'), table_name='compra')
    op.drop_table('compra')
    op.drop_index(op.f('ix_carrito_id'), table_name='carrito')
    op.drop_table('carrito')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_pedidoEnvio_id'), table_name='pedidoEnvio')
    op.drop_table('pedidoEnvio')
    op.drop_index(op.f('ix_pedidoCupon_id'), table_name='pedidoCupon')
    op.drop_table('pedidoCupon')
    op.drop_index(op.f('ix_entidad_id'), table_name='entidad')
    op.drop_table('entidad')
    # ### end Alembic commands ###
