"""fields are too shorts

Revision ID: d769a3e7daf2
Revises: 6719cf079aa2
Create Date: 2025-11-27 22:16:47.948782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd769a3e7daf2'
down_revision: Union[str, None] = '6719cf079aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compraAbono', 'valor',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=32, asdecimal=2),
               existing_nullable=False)
    op.alter_column('producto', 'estado',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('producto', 'imagenUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto', 'imagenUrl',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('producto', 'estado',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('compraAbono', 'valor',
               existing_type=sa.Float(precision=32, asdecimal=2),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    # ### end Alembic commands ###
