version: '3.8'

services:
  db:
    image: mariadb:11.4
    container_name: fastapi-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: floristeria  # Cambiado de fastapi_db a floristeria
      MARIADB_USER: fastapi_user
      MARIADB_PASSWORD: fastapi_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://fastapi_user:fastapi_password@db:3306/floristeria  # Cambiado a floristeria
      - MYSQL_HOST=db
      - MYSQL_USER=fastapi_user
      - MYSQL_PASSWORD=fastapi_password
      - MYSQL_DB=floristeria  # Cambiado a floristeria
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app

volumes:
  mariadb_data: